// Route Paths
export const ENDPOINT = {
  PUBLIC: {
    HOME: '/',
    LOGIN: '/login',
    REGISTER: '/register',
    PRODUCTS: '/api/products',
    CONTACT: '/api/public/contact',
    ENQUIRY: '/api/public/enquiry',
  },
  PRIVATE: {
    DASHBOARD: '/dashboard',
    PROFILE: '/profile',
    SETTINGS: '/settings',
  },
  API: {
    AUTH: {
      LOGIN: '/api/auth/login',
      LOGOUT: '/api/auth/logout',
      REGISTER: '/api/auth/register',
      PROFILE: '/api/auth/profile',
      GET_PROFILE: '/api/auth/me',
    },
    DELIVERY: {
      CREATE: '/api/deliveries',
      GET_ALL: '/api/deliveries',
      GET_BY_ID: (id) => `/api/deliveries/${id}`,
      UPDATE: (id) => `/api/deliveries/${id}`,
      STATS: '/api/deliveries/stats',
      CANCEL: (id) => `/api/deliveries/${id}/cancel`,
      AUDIT_LOGS: '/api/deliveries/audit-logs/me',
      AUDIT_LOG_BY_ID: (id) => `/api/deliveries/audit-logs/${id}`,
    },
    INVOICE: {
      GET_ALL: '/api/invoices',
      GET_BY_ID: (id) => `/api/invoices/${id}`,
      EXPORT_PDF: (id) => `/api/invoices/${id}/export/pdf`,
    },
    PRICING: {
      GET_ALL: '/api/admin/pricing-tiers',
      CREATE: '/api/admin/pricing-tiers',
      GET_BY_ID: (id) => `/api/admin/pricing-tiers/${id}`,
      UPDATE: (id) => `/api/admin/pricing-tiers/${id}`,
      DELETE: (id) => `/api/admin/pricing-tiers/${id}`,
    },
    ADMIN_INVOICE: {
      GET_ALL: '/api/admin/invoices',
      GET_BY_ID: (id) => `/api/admin/invoices/${id}`,
      CREATE: '/api/admin/invoices',
      GENERATE_ALL: '/api/admin/invoices/generate-all',
      UPDATE: (id) => `/api/admin/invoices/${id}`,
      DELETE: (id) => `/api/admin/invoices/${id}`,
      EXPORT_PDF: (id) => `/api/admin/invoices/${id}/export/pdf`,
      SEND_EMAIL: (id) => `/api/admin/invoices/${id}/send`,
      UPDATE_STATUS: (id) => `/api/admin/invoices/${id}/status`,
    },
    ADMIN_AUDIT: {
      GET_ALL: '/api/admin/audit-logs',
      GET_BY_ID: (id) => `/api/admin/audit-logs/${id}`,
    },
    ADMIN_CONTACT: {
      GET_ALL: '/api/admin/contacts',
      DELETE: (id) => `/api/admin/contacts/${id}`,
      MARK_READ: (id) => `/api/admin/contacts/${id}/mark-read`,
    },
    ADMIN_ENQUIRY: {
      GET_ALL: '/api/admin/enquiries',
      DELETE: (id) => `/api/admin/enquiries/${id}`,
      MARK_READ: (id) => `/api/admin/enquiries/${id}/mark-read`,
    },
    ADMIN_SETTINGS: {
      STATUS_SUMMARY: '/api/admin/settings/status/summary',
      GET_ALL: '/api/admin/settings',
      UPDATE_COMPANY: '/api/admin/settings/company',
      UPDATE_BANKING: '/api/admin/settings/banking',
      UPDATE_SYSTEM: '/api/admin/settings/system',
      INVOICE_GEN_CONFIG: '/api/admin/settings/invoice-generation',
    },
  },
};
